### ISSUE TITLE
UI is being cut off upon Window Resize (Chrome, Microsoft Edge)

### ISSUE THREAD

**Issue by jenb2** [NIH-OIR/CHIRP_LLM#145]
![image](https://github.com/user-attachments/assets/e1c3ee53-c00e-404b-8215-31c463564de4)

Right side graphics/UI is being cut off when you resize the Window Smaller.

![image](https://github.com/user-attachments/assets/28864bf1-e739-41f1-8d79-6919dbacaba1)

Bottom/Chat & Left Chat Log is cut off when you resize to a certain width.

**Comment by ylang-nih** [comment]
This can also reproduce on Safari
<img width="1112" alt="Screenshot 2024-12-02 at 1 53 42 PM" src="https://github.com/user-attachments/assets/70f94bec-cdf7-4386-9884-0a41af96e002">

**Comment by lilyfanNIH** [comment]
fixed in issue-151
