### ISSUE TITLE
Add TRAINING & SUPPORT Link

### ISSUE THREAD

**Issue by jenb2** [NIH-OIR/CHIRP_LLM#18]
This will link to another Sharepoint page that Steevenson's team has created.
Dr. Fann wants this to be in a different color so that it's distinguished against the other links.

**Comment by lilyfanNIH** [comment]
Prompt engineering guide -
[https://nih.sharepoint.com/sites/OD-CDATechnologyAvailabilityGuideCTAG/SitePages/Prompt-Engineering.aspx](https://nih.sharepoint.com/sites/OD-CDATechnologyAvailabilityGuideCTAG/SitePages/Prompt-Engineering.aspx?xsdata=MDV8MDJ8fDg4OTRkM2I2ZGNhYzQwNjVmZjNjMDhkY2M4M2Y4MjI3fDE0Yjc3NTc4OTc3MzQyZDU4NTA3MjUxY2EyZGMyYjA2fDB8MHw2Mzg2MDU0MjIyNzE5MjE5ODB8VW5rbm93bnxWR1ZoYlhOVFpXTjFjbWwwZVZObGNuWnBZMlY4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaVYybHVNeklpTENKQlRpSTZJazkwYUdWeUlpd2lWMVFpT2pFeGZRPT18MXxMMk5vWVhSekx6RTVPamszTXprek9XUXdMV1F3TW1JdE5HWXpOQzA0TlRJM0xURTFZbVZtWVRFMFpXVm1NVjlsWXpZNE5UUmhaQzFpWWpGaExUUTJOekl0T0dNNE15MDVOV05rWTJZellqZGlZVFpBZFc1eExtZGliQzV6Y0dGalpYTXZiV1Z6YzJGblpYTXZNVGN5TkRrME5UUXlOakkwTnc9PXwzY2Q2MTA4NTAxMzg0NmM2OWNmMDA4ZGNjODNmODIyNXwyOGM1NTY1NDQ0NDc0MjdlYjQ5NDY5OGYxYWRhYTFmNg%3D%3D&sdata=VnJ2dnVaUTFwT3RWNXVDSEtzWWdENHV3cmNDYmN0cHh4enV1TVZNSU9taz0%3D&ovuser=14b77578-9773-42d5-8507-251ca2dc2b06%2Cfanl5%40nih.gov)

**Comment by lilyfanNIH** [comment]
AI Guidance - https://nih.sharepoint.com/sites/OD-CDATechnologyAvailabilityGuideCTAG/SitePages/AIGuidance_FoundationalInformationGenerativeAIRisks.aspx?xsdata=MDV8MDJ8fGJmNTVmZTFkZGEyNTRiZTFhYjk3MDhkY2MyZWYyYjI0fDE0Yjc3NTc4OTc3MzQyZDU4NTA3MjUxY2EyZGMyYjA2fDB8MHw2Mzg1OTk1Nzk2NTY1NjM2MDd8VW5rbm93bnxWR1ZoYlhOVFpXTjFjbWwwZVZObGNuWnBZMlY4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaVYybHVNeklpTENKQlRpSTZJazkwYUdWeUlpd2lWMVFpT2pFeGZRPT18MXxMMk5vWVhSekx6RTVPamszTXprek9XUXdMV1F3TW1JdE5HWXpOQzA0TlRJM0xURTFZbVZtWVRFMFpXVm1NVjltWXpFMU16ZzJZUzB3TlRKakxUUmxNMk10WWpreE15MDNOV1JoTURoak5qYzFObUZBZFc1eExtZGliQzV6Y0dGalpYTXZiV1Z6YzJGblpYTXZNVGN5TkRNMk1URTJORFUwT1E9PXxhZGY4ZTkzOGEzODM0NTNmNDk0NzA4ZGNjMmVmMmIyMnw0YTc4MDk2N2Y0NjM0YWZhODJhMmNjYmJmNDExNWRmYw%3D%3D&sdata=Qkk0R09aYzFsOWgyWUlsQzdEc083U0w0Y0tjaGxoaFIxNWRVRU1zZ1E3Yz0%3D&ovuser=14b77578-9773-42d5-8507-251ca2dc2b06%2Cjenb2%40nih.gov&OR=Teams-HL&CT=1724945444026&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIxNDE1LzI0MDcxMTI4ODI1IiwiSGFzRmVkZXJhdGVkVXNlciI6ZmFsc2V9
