### ISSUE TITLE
Implement PI Scrubber

### ISSUE THREAD

**Issue by lilyfanNIH** [NIH-OIR/CHIRP_LLM#21]
Need to implement following user input scrubbing to detect PII info. Here is the code in Python:
======================
import streamlit as st
import os
from openai import OpenAI
import scrubadub

### Initialize OpenAI client with your API key
client = OpenAI(api_key=os.environ.get("OPENAI_API_KEY"))

### Function to check and scrub PII from the prompt
def scrub_prompt(prompt):
    scrubber = scrubadub.Scrubber()
    scrubbed_prompt = scrubber.clean(prompt)
    return scrubbed_prompt

### Streamlit app
st.title("Prompt guard - PII/PHI Scrubber for AI interfaces.")
st.sidebar.image("/Users/mikenalls/Desktop/prompt_guard/etc/prompt_guard_logo.jpg", use_column_width=True)
st.sidebar.image("/Users/mikenalls/Desktop/prompt_guard/etc/DT_logo.jpg", use_column_width=True)

### User input
user_prompt = st.text_area("Enter your prompt for the AI:")

if st.button("Submit"):
    if user_prompt:
        scrubbed_prompt = scrub_prompt(user_prompt)
        
        if scrubbed_prompt != user_prompt:
            st.warning("Potential PII detected in the prompt. The prompt will be scrubbed before being sent to the AI.")
            st.write("Scrubbed Prompt:")
            st.write(scrubbed_prompt)
        else:
            st.success("No PII detected in the prompt.")
            scrubbed_prompt = user_prompt

        # Send scrubbed prompt to OpenAI
        response = client.chat.completions.create(
        messages=[
            {"role": "user", "content": f"From your scrubbed prompt if necessary: {scrubbed_prompt}"}
        ],
        model="gpt-4",
    )

        st.write("ChatGPT Response:")
        st.text_area("", response.choices[0].message.content)
    else:
        st.error("Please enter a prompt.")
==============

**Comment by jenb2** [comment]
Robyn tested some of the code within Chirp yesterday. See the latter half of this recording here:

https://nih.sharepoint.com/:v:/r/sites/OD-Crispi-LLM-Pilot/Shared%20Documents/LLM%20Education%20and%20Training/CHIRP%20related%20recordings/Scrubber%20Install%20w%20Robyn%20%5BC%5D-20240820_145754-Meeting%20Recording.mp4?csf=1&web=1&e=BYSshW
