### ISSUE TITLE
UI update - add About to the left navigation

### ISSUE THREAD

**Issue by lilyfanNIH** [NIH-OIR/CHIRP_LLM#5]
Add About Link which will link to new page with about information

[](url)
[IRP LLM Chirp UI Design Screens (1).docx](https://github.com/user-attachments/files/16564881/IRP.LLM.Chirp.UI.Design.Screens.1.docx)

**Comment by jenb2** [comment]
Update from ABOUT to ABOUT CHIRP

**Comment by lilyfanNIH** [comment]
updated in updating icon branch
