### ISSUE TITLE
Remove "OPENAI" from landing page description

### ISSUE THREAD

**Issue by jenb2** [NIH-OIR/CHIRP_LLM#53]
Since Chirp includes LLMs from multiple companies, we should change the language and remove the "OpenAI" text.

Current:
Landing Page: "This Chatbot is designed to provide users with general information through OpenAI's Large Language Models."
Change to:
Landing Page: "This chatbot is designed to provide users with general information through different Large Language Models"

**Comment by lilyfanNIH** [comment]
Updated in config file
