### ISSUE TITLE
Unable to upload PDF in Chrome MacOS 14.6.1

### ISSUE THREAD

**Issue by jenb2** [NIH-OIR/CHIRP_LLM#62]
I am one of the pilot users of CHIRP. I am having difficulty uploading pdfs to the chatbot for summarization. I am using Chrome on MacOS 14.6.1.

 When I click on the paper clip, I am able to select the pdf on my desktop, but when I then click “open” nothing happens, and the pdf is not being uploaded.

**Comment by lilyfanNIH** [comment]
This is the user issue. after uploading the file, the user need to let the AI model know what to do next, such as summarize the upload file, what's the content.
