### ISSUE TITLE
Chatbot textbox size to be fixed

### ISSUE THREAD

**Issue by abhradeepNIH** [NIH-OIR/CHIRP_LLM#65]
Adjusting the textbox size, misaligns the CHIRP UI, we may want to fix the text box size and remove the adjustment feature.

**Comment by lilyfanNIH** [comment]
do you have screenshot to specify this issue? not really get what's the issue

**Comment by abhradeepNIH** [comment]
If you move your mouse pointer to the right corner the pointer changes to the "drag" sign and you are able to resize the text box :
![image](https://github.com/user-attachments/assets/6d388d25-6e50-4152-89a7-8face14be8a5)
